### ISSUE TITLE
Does npm install need python env variable?

### ISSUE THREAD

**Issue by bippeishan** [maxnachlinger/redux-websocket-example#3]
When I run npm install 'level ' and 'level-session-store', some error info will show like this:

prebuild ERR! configure error
prebuild ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! stack     at PythonFinder.failNoPython (C:\githubres\redux-websocket-example\server\node_modules\node-gyp\lib\configure.js:483:19)
prebuild ERR! stack     at PythonFinder.<anonymous> (C:\githubres\redux-websocket-example\server\node_modules\node-gyp\lib\configure.js:508:16)
prebuild ERR! stack     at C:\githubres\redux-websocket-example\server\node_modules\graceful-fs\polyfills.js:284:29
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
prebuild ERR! not ok
prebuild ERR! build Error: Can't find Python executable "python", you can set th
e PYTHON env variable.
prebuild ERR! build     at PythonFinder.failNoPython (C:\githubres\redux-websock
et-example\server\node_modules\node-gyp\lib\configure.js:483:19)
prebuild ERR! build     at PythonFinder.<anonymous> (C:\githubres\redux-websocke
t-example\server\node_modules\node-gyp\lib\configure.js:508:16)
prebuild ERR! build     at C:\githubres\redux-websocket-example\server\node_modu
les\graceful-fs\polyfills.js:284:29
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:152:21)

Should I install Pathon at first?I think it is too complicated!

**Comment by maxnachlinger** [comment]
If you think it's too complicated, I wouldn't do it :) Lots of nodejs projects and libraries rely on `node-gyp` so if you want to develop in this ecosystem it would probably be worth following [the instructions here to setup `node-gyp`](https://github.com/nodejs/node-gyp)
