### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by dulangaheshan** [maxnachlinger/redux-websocket-example#32]
it throw these kind of errors

[0] 'np' is not recognized as an internal or external command,
[0] operable program or batch file.
[1] 'run' is not recognized as an internal or external command,
[1] operable program or batch file........

**Comment by maxnachlinger** [comment]
This repo doesn't use an `np` command anywhere. Did you mean `npm` ? In case you did, please ensure you have nodejs and npm installed and in your path.

**Comment by dulangaheshan** [comment]
npm install working fine and after that i tried npm start it throws those errors

**Comment by maxnachlinger** [comment]
Please re-pull and run `npm i && npm start` and paste the output you get in a code block. Here's a good example of a code block if that helps: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting . Your version of node would also help I guess. You can get that via `node -v`

**Comment by maxnachlinger** [comment]
Go ahead and create a new issue once you have this output and I'll see if anything jumps out.
