### ISSUE TITLE
What the reason behind the remplacement of socket.io ?

### ISSUE THREAD

**Issue by t-mdo** [maxnachlinger/redux-websocket-example#7]

**Comment by maxnachlinger** [comment]
There are several benefits:
- browser support - [most browsers now support websockets natively](https://caniuse.com/#feat=websockets)
- which means we get a smaller resulting bundle size - which is a concern for front-end JS dev

I've you'd like to use socket.io, go ahead and fork this repo and add it into your fork. Open source is awesome like that :)

**Comment by t-mdo** [comment]
Nah, there was not hidden judgment behind my question. I was only curious to know the reasoning behind this.
Thanks.
